[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8000}"
